### ISSUE TITLE
Transparency not working on UWP

### ISSUE THREAD

**Issue by MorneZaayman** [jamesmontemagno/ImageCirclePlugin#77] opened 2018-11-12 18:16 UTC
## Bug Information
Version Number of Plugin: 3.0.0.5
Device Tested On: Windows 10 Pro, Version 1803
Simulator Tested On: N/A
Version of VS: 15.8.8
Version of Xamarin: 3.3.0.967583

### Steps to reproduce the Behavior
When creating a CircleImage in UWP witha FillColor property defined, and an image with transparency, the transparency changes to white, hiding the FillColor behind the image.
### Expected Behavior
The FillColor shows behind the image in the parts of the image that are transparent.
### Actual Behavior
The transparent parts of the image get rendered as white, covering the FillColor.
### Code snippet
`
<circleimage:CircleImage
                                    x:Name="SelectionImage"
                                    Aspect="AspectFill"
                                    IsVisible="True" 
                                    Source="{Binding Icon}"
                                    FillColor="{Binding FillColor}"
                                    BorderThickness="3"
                                    WidthRequest="30"
                                    HeightRequest="30"
                                    VerticalOptions="Center"
                                    Margin="0,5,30,0"
                                    Grid.Row="0"
                                    Grid.RowSpan="2"
                                    Grid.Column="1"/>
`
### Screenshots
White/Transparent images are between the <-- and -->

Example image: -->![icon_tick](https://user-images.githubusercontent.com/25976312/48366234-dd3c8480-e6b5-11e8-8eca-03d31ea5c929.png)<--
Expected (From Android build): 
<img width="49" alt="expected" src="https://user-images.githubusercontent.com/25976312/48366732-64d6c300-e6b7-11e8-9eae-0466eb5eefb2.PNG">
Actual: 
--> <img width="43" alt="actual" src="https://user-images.githubusercontent.com/25976312/48366750-6f915800-e6b7-11e8-9ef1-60a28c4041f8.PNG"><--

**Comment by jamesmontemagno** [comment] 2019-01-16 23:01
Duplicate of : https://github.com/jamesmontemagno/ImageCirclePlugin/issues/1 however I don't think it can be solved after looking at the code. You can stack 2 on top of each other.

**Closed as completed** 2019-01-16 23:01 UTC
